### ISSUE TITLE
Region 3 Problems

### ISSUE THREAD

**Issue by smr160holtec** [jjgomera/iapws#12]
Hello,
When using IAPWS97 I am having a problem with Px initialization. It seems that if x==1 or x==0 returns properties for x==0 only if P>16.529 MPa. Example:
`>>> from iapws import IAPWS97`
`>>> satL=IAPWS97(P=17.0,x=0)`
`>>> satL.h`
`1690.0370435729556`
`>>> satV=IAPWS97(P=17.0,x=1)`
`>>> satV.h`
`1690.0370435729556`

The results should not be identical. I expected satV.h to be about 2547.

I am using python 3.4.2 and iapws 1.1.1. I originally got iapws from pip. I saw there was a change made to the Px routine with a commit about a week ago. I tried implementing this but I don't think it fixes my problem.
Let me know if you need anything else.
Thanks

**Comment by jjgomera** [comment]
You are right, i make this bug solving the bug you are talking about.
Fix in las commit, I think

**Comment by smr160holtec** [comment]
Thanks. It appears to be functioning correctly now.

**Comment by jH44** [comment]
There is still a bug for region 3, at least for specific volume (was trying to plot a P-v diagram for students)
You search rho from P,T without considering the value of x ! (iapws97.py, around line 2877, version 1.2.2)
but rho(x=0) is not equal to rho(x=1) !!
I think you need to search rho on both sides of P(T) and :
rho = x*rho1+(1.-x)*rho2
(at least for specific volume)

Anyway thanks for this work ...
