### ISSUE TITLE
Usage of IAPWS95(): Decreasing pressure with constant temperature and decreasing specific volume 

### ISSUE THREAD

**Issue by ckaldemeyer** [jjgomera/iapws#13]
Thanks for your implementation! It has been a help for me to do some calculations.

But while using the scientific formulation IAPWS-95 to plot 3D a PvT diagram, I became sceptical about the output data:

    IAPWS95(T=250+273.15, v=10).P
    Out[6]: 2.2080623654368261

    IAPWS95(T=250+273.15, v=5).P
    Out[7]: 1.156479877280217

    IAPWS95(T=250+273.15, v=1).P
    Out[8]: 0.2394463065087358

    IAPWS95(T=250+273.15, v=0.1).P
    Out[9]: 0.024124428435807685

Shouldn't the pressure increase with a decreasing specific volume like in every T,s-diagram?

Cheers
Cord

**Comment by jjgomera** [comment]
Hi,
Fixed now in last commit, really a nonsense, the specific volume input isn't converted to density
thanks for feedback and excuse me for answer too late.

**Comment by ckaldemeyer** [comment]
A bit late (somehow missed it)...thanks!!
