### ISSUE TITLE
Significant performance difference between IAPWS95 and IAPWS97

### ISSUE THREAD

**Issue by rkingsbury** [jjgomera/iapws#14]
I was trying to add iapws to another project when I noticed that IAPWS95 takes significantly longer to initialize than IAPWS97. I had hope to use -95 because it can calculate the density of water below zero degrees C, whereas 97 cannot.

```
In [5]: from iapws import IAPWS95

In [6]: %timeit h2o=IAPWS95(P=0.1,T=298)
10 loops, best of 3: 40.5 ms per loop

In [7]: from iapws import IAPWS97

In [8]: %timeit h2o=IAPWS97(P=0.1,T=298)
1000 loops, best of 3: 226 µs per loop

```

I understand there are probably underlying differences in the algorithms, but can this huge performance difference be improved?

**Comment by jjgomera** [comment]
Hi, obviously IAPWS95 is more complex mathematically. I've tried to use initial rho value for iteration, use specific iteration algorithm as [1], or reduce iteration cycle, but the iteration is the speed bottleneck, and scipy fsolve function is my best option.

The IAPWS97 implementation define the range of validity for T > 273,15.  Anyway you can avoid that limitation and use it for that liquid at high pressure

```
In [1]: from iapws import IAPWS95

In [2]: from iapws.iapws97 import _Region1

In [3]: 1./_Region1(273, 0.1)["v"]
Out[3]: 999.8332748158809

In [4]: IAPWS95(P=0.1, T=273).rho
Out[4]: 999.8320431594719
```

Obviously the values must be checked because is out of its range of validate.


[1]: Akasaka, Ryo. "A Reliable and Useful Method to Determine the Saturation State from Helmholtz Energy Equations of State", Journal of Thermal Science and Technology 3, pag. 442 (2008

**Comment by fwitte** [comment]
Hi,
I experienced huge differences in performance regarding region 4. I need to calculate the properties for steam from p and h in -95 (as I require derivatives). Performing the following lines of code, I get a huge difference in calculation times.
```
In [1]: two_phase_95=IAPWS95(P=1,h=2300)
In [2]: two_phase_97=IAPWS97(P=1,h=2300)
In [3]: two_phase_95_a=IAPWS95(P=1,h=2300,rho0=two_phase_97.rho)
In [4]: two_phase_95_b=IAPWS95(P=1,x=two_phase_95.x)
```
time in seconds:
```
Out [1]: 0.6418745517730713
Out [2]: 0.0014805793762207031
Out [3]: 0.5771079063415527
Out [4]: 0.09607577323913574
```
Is there a way to get faster results in IAPWS95? Unfortunately it is not possible for me to use x as an input parameter. Maybe there is a way to implement a starting value for x?
Greetings and have a nice day!

**Comment by jjgomera** [comment]
First of all, what derivative properties do you need? IAPWS97 implement partial derivative:

```
In [1]: from iapws import IAPWS97
In [2]: st = IAPWS97(P=1, h=2300)
In [3]: st.derivative("P", "v", "T", st.Vapor)   # dP/dv |T in vapour phase
Out[3]: -4.722733040050645
In [4]: st.derivative("P", "v", "T", st.Liquid)   # dP/dv |T in liquid phase
Out[4]: -1175253.1046164865
```

About increase performance, maybe let the user define if the point is in two phase region can improve the speed, I will work in that.

**Comment by fwitte** [comment]
Hi, hope you had a nice weekend.
Thank you for your help. In the two-phase-region I need to calculate dT/dP at constant h, in other regions I have to calculate dh/dP at constant T. For now I changed to IAPWS97 and implemented derivatives with the central difference quotient, like this:
```
def dhdp_T(p,h,delta):
    u=IAPWS97(P=(p+delta)/10,T=IAPWS97(P=(p+delta)/10,h=h/1000).T)
    l=IAPWS97(P=(p-delta)/10,T=IAPWS97(P=(p-delta)/10,h=h/1000).T)
    return (u.h-l.h)/(2*delta)
```
I will try your version, too.

**Comment by jjgomera** [comment]
I'm try to optimize the root finding algorithm for IAPWS95. I can't imagine other optimization
