### ISSUE TITLE
Sigma does not work in iapws97

### ISSUE THREAD

**Issue by edelperi** [jjgomera/iapws#15]
Dear Juan,
Surface tension sigma  property in IAPWS97  does not work. 
Objet has no attribute in IAPWS97 
I installed IAPWS with pip, in Linux redhat 

Congratulattions for your work,

Kind regards,

Eugenio.

**Comment by jjgomera** [comment]
Hi,

This issue was solved several months ago, issue #8, but I didn't create a new release in pip with last bug fix, so there the bug isn't fixed yet. Try to install the last commit in github: https://github.com/jjgomera/iapws/archive/master.zip

Thanks for feedback, Cheers, Juanjo.
