### ISSUE TITLE
error in specific temperature calculation

### ISSUE THREAD

**Issue by dsysoev** [jjgomera/iapws#18]
I cannot calculate property for specific temperature

`from iapws import IAPWS97`
`IAPWS97(T=623.15, x=0).t`
`---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-15-f5bf914a7c2c> in <module>()
----> 1 IAPWS97(T=623.15, x=0).t

/usr/local/lib/python2.7/dist-packages/iapws/iapws97.pyc in __init__(self, **kwargs)
   2690     def __init__(self, **kwargs):
   2691         self.kwargs = IAPWS97.kwargs.copy()
-> 2692         self.__call__(**kwargs)
   2693 
   2694     def __call__(self, **kwargs):

/usr/local/lib/python2.7/dist-packages/iapws/iapws97.pyc in __call__(self, **kwargs)
   2697         if self.calculable:
   2698             self.status = 1
-> 2699             self.calculo()
   2700             self.msg = "Solved"
   2701 

/usr/local/lib/python2.7/dist-packages/iapws/iapws97.pyc in calculo(self)
   2891                 propiedades = _Region4(P, x)
   2892             elif P > Ps_623 and x in (0, 1):
-> 2893                 rho = 1./_Backward3_v_PT(P, T)
   2894                 propiedades = _Region3(rho, T)
   2895             elif Tt <= T <= Tc and x == 0:

/usr/local/lib/python2.7/dist-packages/iapws/iapws97.pyc in _Backward3_v_PT(P, T)
   1637             region = "t"
   1638 
-> 1639     return _Backward3x_v_PT(T, P, region)
   1640 
   1641 

UnboundLocalError: local variable 'region' referenced before assignment`

**Comment by jjgomera** [comment]
Solved in last commit, I think, try it

**Comment by dsysoev** [comment]
It works. Thank you!
