### ISSUE TITLE
Increased performance up to 5 times

### ISSUE THREAD

**Issue by dsysoev** [jjgomera/iapws#20]
I found a performance bottleneck in the IAPWS97 module.
Here my analysis (in Jupyter notebook):

For whole function on my machine it take (tested in Region 2):
```python
%timeit iapws97.IAPWS97(P=3., s=6.5)
```
100 loops, best of 3: 9.36 ms per loop

```python
import iapws97
from scipy.optimize import newton

P, s = 3., 6.5
# initial value of Temperature
To = iapws97._Backward2a_T_Ps(P, s)
funcion = lambda T: iapws97._Region2(T, P)["s"]-s
# fsolve
a = %timeit -o -q iapws97.fsolve(funcion, To)[0]
val = iapws97.fsolve(funcion, To)[0]
print("{:10s} {:.4f} {}".format('fsolve', a.best, val))
# newton
a = %timeit -o -q newton(funcion, To)
val = newton(funcion, To)
print("{:10s} {:.4f} {}".format('newton', a.best, val))
```
fsolve       0.0080 564.036985544
newton     0.0005 564.036985544

The bottleneck is in 'fsolve' method which performs 85% of time for whole function. If we change 'fsolve' method to 'newton' we get significant speed improvement.

```python
%timeit iapws97.IAPWS97(P=3., s=6.5)
```
1000 loops, best of 3: 1.36 ms per loop

The [newton](http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.newton.html#scipy.optimize.newton) method is much simpler than [fsolve](http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fsolve.html#scipy.optimize.fsolve) but for given tasks it enough.

**Comment by jjgomera** [comment]
Hi,
Thanks for point me that newton function in scipy library, I didn't know.
I added for several iteration calculation, I can't work in two parameters iterations, anyway it's a great speed improvement. Using the initial parameter from backward equations is a great solution for convergence stability and speed.

**Comment by dsysoev** [comment]
I checked performance of IAPWS97. Now it works ~10 times faster)
