### ISSUE TITLE
IAPWS08 : Computation of ks

### ISSUE THREAD

**Issue by jmflores26** [jjgomera/iapws#26]
Hi, jjgomera,

It seams there is a mistake in the computation of the isentropic compressibility ks in IAPWS08 module (file iapws08.py) if we refer to the document "IAPWS R13-08" (http://www.iapws.org/relguide/seawater.pdf, bottom of page 7):

`self.ks = (prop["gtp"]**2-prop["gt"]*prop["gpp"])/prop["gp"] / \ ...`

should be:

`self.ks = (prop["gtp"]**2-prop["gtt"]*prop["gpp"])/prop["gp"] / \ ...`

What is your opinion ?

Thank you very much for your great and usefull work !
Regards.

**Comment by jjgomera** [comment]
You're right, a tiny typo. Thanks!
