### ISSUE TITLE
Problem with heavy water saturation temprature

### ISSUE THREAD

**Issue by khurrumsaleem** [jjgomera/iapws#33]
Hye. 

I encountered strange behavior (once again, remember #32 ) although I did new installation back then and it solved my problem. This time I am having problem with properties that the boiling is taking place way past the saturation temperature for example saturation temperature at 10 MPa is close to 583K but even if i use hw = D2O(P=10, T=593.15) i still get hw.phase = 'Liquid'. The same thing happens at other pressure values too. 

Am i making some mistake (again)?

**Comment by khurrumsaleem** [comment]
@jjgomera any help will be appreciated

**Comment by jjgomera** [comment]
Excuse for the late answer, holidays in paradise :)

You're right, that's a severe bug in phase determination when TP is used as input parameters. Try with last commit.

Thanks for feedback

**Comment by khurrumsaleem** [comment]
@jjgomera Thanks for the help but I am still seeing the similar result.

![image](https://user-images.githubusercontent.com/5681739/44969293-87e24980-af87-11e8-9177-d5e8c5145956.png)

**Comment by jjgomera** [comment]
I'm no upgrade the version in pip, use the last commit from github:

git clone https:/github.com/jjgomera/iapws.git

**Comment by khurrumsaleem** [comment]
@jjgomera thank you very much. I checked the calculation again using installation directly from git and it works fine now. 

You can close issue #33 now.
