### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by meylone** [jjgomera/iapws#34]
It would be useful to add a few things to the documentations:
Units of the inputs (pressure, temperature, ...)
Examples for known entropy (P,S),(T,S)

**EDIT**
I found this link that explains how to use your library very well. You might want to add it to the read me section:
http://kitchingroup.cheme.cmu.edu/blog/2013/02/28/Meet-the-steam-tables/

**Comment by jjgomera** [comment]
The units in input parameter are in documentation (https://iapws.readthedocs.io/en/latest/iapws.iapws97.html#iapws.iapws97.IAPWS97), but you're right, i have to improve documentation. Working on that...

**Comment by jjgomera** [comment]
Try now, I've clean the documentation and improve access to main class from index.
