### ISSUE TITLE
Change iapws license to MIT instead of GPL

### ISSUE THREAD

**Issue by arthursoprana** [jjgomera/iapws#39]
Hi. I wonder if is it possible for this project to be distributed under the MIT license instead of GPL. We would like very much to use it in our project, however the GPL license is a blocker.

I hope that this could be possible. Best regards.

**Comment by jjgomera** [comment]
Sorry but I like gpl license by moral ideology. I use in all my project and obviously i would like find more and more software licensed with that over internet.
