### ISSUE TITLE
'IAPWS97' object has no attribute '_PSat_T'

### ISSUE THREAD

**Issue by xiefeisd** [jjgomera/iapws#44]
我得到一个错误：
\>\>\> r4 = IAPWS97(P=0.101325,T=300)
\>\>\> r4._PSat_T(500)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'IAPWS97' object has no attribute '_PSat_T'

**Comment by xiefeisd** [comment]
我知道了，我不能调用饱和压力函数。

**Comment by jjgomera** [comment]
_PSat_T is a function in module iapws97, its a internal function of iapws usable too out of box:

```
from iapws.iapws97 import _PSat_T
_Psat_T(300)
```
