### ISSUE TITLE
Entropy calculates improperly at particular values

### ISSUE THREAD

**Issue by Ickaser** [jjgomera/iapws#46]
The entropy calculation at certain values, around P=.7 bar and T=312 K, goes haywire.

![image](https://user-images.githubusercontent.com/47340776/74489895-03863c80-4e84-11ea-84a7-9c7233ce8025.png)

The code producing this is as follows:
`
import matplotlib.pyplot as plt  
import numpy as np  
from iapws import IAPWS97  
P = .7 # bar  
T_arr = np.linspace(300, 320) # kelvin  
plt.plot(T_arr, [IAPWS97(P=P4, T=T).s for T in T_arr])
`

**Comment by jjgomera** [comment]
What's the problem? The step in plot is the expected result of the vaporization, around 312K at 0.0007 MPa. If you do the example but at atmospheric pressure (0.101325 MPa) the step will be near at 373.15 K.

Really you are ploting a isobar in this plot, rotated but same to blue line in plot

![Ts](https://raw.githubusercontent.com/jjgomera/iapws/master/images/Ts.png)

**Comment by Ickaser** [comment]
You're right. After talking with a classmate I realized the problem, and I hadn't had time to fix the issue. Thanks nonetheless!
