### ISSUE TITLE
Incorrect units for wavelength on readthedocs.io IAPWS97

### ISSUE THREAD

**Issue by k547** [jjgomera/iapws#59]
Issue on: https://iapws.readthedocs.io/en/latest/iapws.iapws97.html#

Currently reads (x2 instances):
l ([float](https://docs.python.org/3/library/functions.html#float), optional) – Wavelength of light, for refractive index, [nm]

Should read:
l ([float](https://docs.python.org/3/library/functions.html#float), optional) – Wavelength of light, for refractive index, [um]

IAPWS95 docs show units as [mm]

**Comment by jjgomera** [comment]
Really there is a bug in both documentation, the correct input units for wavelength of light for refractive index is in micrometer, fixed

Thanks for report
