### ISSUE TITLE
DeprecationWarning: scipy.exp is deprecated and will be removed in SciPy 2.0.0, use numpy.exp instead

### ISSUE THREAD

**Issue by rkingsbury** [jjgomera/iapws#63]
Hello, thank you for maintaining this very useful package. It appears that `scipy.exp` needs to be replaced by `numpy.exp` to avoid a large number of `DeprecatioWarning`.

**Comment by jjgomera** [comment]
Done, upload new release to pypi, https://pypi.org/project/iapws/

**Comment by rkingsbury** [comment]
Thank you for the quick fix! I can't check the version at the moment (was running on a different computer), but I had just `pip install`'ed it a few days ago.
