### ISSUE TITLE
Error calculating T from IAPWS95(u,v).T

### ISSUE THREAD

**Issue by sepjvd** [jjgomera/iapws#67]
Hi,

I am trying to calculate the temperature using u and v  in a loop. 
` nexttemp = IAPWS95(v = Dv, u = Du).T `
In the last steps of loop I received this error: "The iteration is not making good progress, as measured by the improvement from the last ten iterations."
I would appreciate any help!

**Comment by jjgomera** [comment]
I can't reproduce your error, I don't have the values for Dv and Du. Maybe as the error say the iteration don't converge

Using other input parameters:

In [1]: from iapws import IAPWS95

In [2]: st1 = IAPWS95(T=300, x=0.5)

In [3]: st2 = IAPWS95(u=st1.u, v=st1.v)
...
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:178: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)

In [4]: print(st1.T, st2.T)
300 300.00000000054473

In [5]: print(st1.x, st2.x)
0.5 0.5000000000002287

The u-v pair don't have any optimized method for initial values so it's more prone to convergence error. In my case fail with some u-v pair before meet a solution with another initial values
