### ISSUE TITLE
 The calculation of the isoentropic exponent  is  error?

### ISSUE THREAD

**Issue by thermalogic** [jjgomera/iapws#69]
when T=813.15k, p=24MPa, the isoentropic exponent is 1.301

but the value from the package is  0.8257746524996094

The calculation of the isoentropic exponent  is  error?

**Comment by jjgomera** [comment]
You are right, fixed now using the definition given [here](https://www.inglenookeng.com/isentropic-expansion-coefficient-calculation/).
Thanks!!
