### ISSUE TITLE
Unexpected results from IAPWS97 class

### ISSUE THREAD

**Issue by Nino-ndrk** [jjgomera/iapws#73]
Hello,

I would like to report some issues in the iapws97 class implementation. 
I am creating a tabulated set of properties and I found something weird in certain conditions.
By providing pressure and enthalpy as input tuple, it seems that the region assignment is not done correctly for pressures in the range between 16.53 to 21.5 MPa, when closer to the saturation curve.
The problems relate to both the vapour and liquid phases, which behave differently. 

* For the vapour phase, for example:

```
>>> print(IAPWS97(P=21, h=2356).T, IAPWS97(P=21, h=2254).T, IAPWS97(P=21, h=2611).T)
643.2115113008617 642.9773430240623 642.9773430240623
```

at fixed pressure, by increasing the enthalpy, the temperature firstly increases as expected, but at a certain non identified point, 
it decreases suddenly to saturation for a limited range of enthalpies, as shown by the last term in the snippet above. The enthalpy related to the last term (2611 kJ/kg) is higher than the saturated vapour one according to:

```
>>> print(IAPWS97(P=21, x=1).h)
2337.5432149151534
```

* For the liquid phase, even though I chose enthalpies below liquid saturation:

```
>>> print(IAPWS97(P=20.087, x=0).h)
1831.8754182819403
```

the retrieved temperature values are, as expected, below the saturation one: 

```
>>> print(IAPWS97(P=20.087, h=1648).T, IAPWS97(P=20.087, h=1732).T, IAPWS97(P=20.087, h=1832).T, IAPWS97(P=20.087, h=1991).T)
623.4616860904063 632.5185280501452 639.2585959405147 639.2585959405147
```

but the resulting phases are wrong since the given liquid phase is empty and the one filled is the vapor:

```
>>> print(IAPWS97(P=20.087, h=1648).Liquid.cp, IAPWS97(P=20.087, h=1732).Liquid.cp, IAPWS97(P=20.087, h=1832).Liquid.cp, IAPWS97(P=20.087, h=1991).Liquid.cp)
None None 18.14379096532676 18.14379096532676
>>> print(IAPWS97(P=20.087, h=1648).Vapor.cp, IAPWS97(P=20.087, h=1732).Vapor.cp)
8.136018950304729 10.950653131497534
```

As a user, I would expect to see a filled liquid phase. Is this related to how the boundary between region 1 and 3 is defined?

* It seems that the package that comes with pip is more than two years old. I would ask you if you planned to update the pip package with your latest modifications soon, it would be nice to have this modification easily installable.

Thank you very much for your useful work.

**Comment by jjgomera** [comment]
Hi, confirmed, maybe a picture is worth a thousand words, using plot.py file to generate a chart

![bug](https://github.com/jjgomera/iapws/assets/1710547/501f94af-cf44-44c0-9abc-6bd3eebb9e61)

working on that!

**Comment by jjgomera** [comment]
Fixed, I think. There was a bad identification of region in P-h input with enthalpy over the maximum range of validity for the p=f(h) for saturation line for region 3.

```
In [1]: from iapws import IAPWS95, IAPWS97
In [2]: print(IAPWS97(P=21, h=2356).T, IAPWS97(P=21, h=2254).T, IAPWS97(P=21, h=2611).T)
643.2115113008617 642.9773430240623 654.6723298002771
```
![Figure_1](https://github.com/jjgomera/iapws/assets/1710547/4e7416dc-bf90-449e-a240-91ca87ff3ac9)


> It seems that the package that comes with pip is more than two years old. I would ask you if you planned to update the pip package with your latest modifications soon, it would be nice to have this modification easily installable.
 
You're right, the pip version is fairly old, with really tiny changes with the version in github, you can install directly from github with:

`pip install git+https://github.com/jjgomera/iapws.git
`

Anyway, you're right, iapws needed a new  updated version in iapws, uploaded, [iapws 1.5.4](https://pypi.org/project/iapws/)

Thanks for feedback

**Comment by Nino-ndrk** [comment]
Thank you for the quick response. I would also like to share another feedback regarding the filling of properties in two-phases region, in near critical conditions. The creation of phases is always done with _Region1 and _Region2 calculation. However, this seems to cause some discontinuities in the evaluation of phase properties at pressures higher than 16.53MPa, as they may need to be evaluated with _Region3. Perhaps something similar to what is done in _Region4 function can be done. That is, include an if statement as a function of temperature before calling the fill() method: 
```
if 623.15 < self.T <= Tc:
    def funcion(rho):
        return _Region3(rho, self.T)["P"] - self.P

    rholo = 1. / _Backward3_sat_v_P(self.P, self.T, 0)
    rhol = fsolve(funcion, rholo)[0]
    liquido = _Region3(rhol, self.T)
    
    rhovo = 1. / _Backward3_sat_v_P(self.P, self.T, 1)
    rhov = fsolve(funcion, rhovo)[0]
    vapor = _Region3(rhov, self.T)
else:
    liquido = _Region1(self.T, self.P)
    vapor = _Region2(self.T, self.P)
self.fill(self.Liquid, liquido)
self.fill(self.Vapor, vapor)
```
This results in: 
![Figure_1](https://github.com/jjgomera/iapws/assets/137185631/92783233-206f-4b6b-bf85-615365562749)

Wouldn't that improve the consistency of the package?

**Comment by jjgomera** [comment]
IAPWS97 use _Region3  for T> 623.15 in region 4, [iapws97](https://github.com/jjgomera/iapws/blob/master/iapws/iapws97.py#L4054)

```
elif self._thermo == "Tx":
    T, x = args
    P = _PSat_T(T)
    if 273.15 <= T < Tc and 0 < x < 1:
        propiedades = _Region4(P, x)
    elif 273.15 <= T <= 623.15 and x == 0:
        propiedades = _Region1(T, P)
    elif 273.15 <= T <= 623.15 and x == 1:
        propiedades = _Region2(T, P)
    elif 623.15 < T < Tc and x in (0, 1):
        rho = 1. / _Backward3_sat_v_P(P, T, x)
        propiedades = _Region3(rho, T)
    elif T == Tc and 0 <= x <= 1:
        propiedades = _Region3(rhoc, Tc)
    else:
        raise NotImplementedError("Incoming out of bound")
    self.sigma = _Tension(T)
    propiedades["x"] = x

```

Can you give me the code to generate that plot, i don´t understand how generate and why that difference in cp value, using a isobar line at 17.2MPa I get this

![Figure_1](https://github.com/jjgomera/iapws/assets/1710547/74979ce0-5395-4ad7-a650-ef5eb3700ec8)

with this code
```
from numpy import linspace
from matplotlib import pyplot
from iapws.iapws97 import IAPWS97

h = linspace(1000, 4000, 100)
cp = []
hs = []

for hi in h:
    state = IAPWS97(P=17.2, h=hi)
    cp.append(state.Vapor.cp)
    hs.append(state.Vapor.h)

pyplot.plot(hs, cp)
pyplot.show()
```

**Comment by Nino-ndrk** [comment]
Hi, of course I was not clear. I was just referring to how the phases are filled after the calculation, if 0 < x < 1, https://github.com/jjgomera/iapws/blob/master/iapws/iapws97.py#L4113 . Also, I saved the arrays in relative pressure and I was wrong, the pressure was 20.8MPa. I got this plot:
![Figure_1](https://github.com/jjgomera/iapws/assets/137185631/6d9697a9-e8f7-4bf4-ae7f-6fb341435953)
with this script: 
```
from numpy import linspace
from matplotlib import pyplot
from iapws.iapws97 import IAPWS97
from iapws_mod.iapws.iapws97 import IAPWS97 as IAPWS97mod

hh = linspace(2000, 4000, 1000)
cp = []
cpmod = []

for hi in hh:
    state = IAPWS97(P=20.8, h=hi)
    cp.append(state.Vapor.cp)
    cpmod.append(IAPWS97mod(P=20.8, h=hi).Vapor.cp)

pyplot.plot(hh, cp)
pyplot.plot(hh, cpmod)
pyplot.show()
```
The modified version has the previously suggested code instead of lines 4113-4116. Anyway, I only noticed relevant differences in cp and densities when very close to the critical point.

**Comment by jjgomera** [comment]
Hi,
great feedback, you're right again!!

I've update the code with your code, although using the backward equation avoiding the fsolve iteration for speed optimization.

**Comment by Nino-ndrk** [comment]
Good to hear you! 
Just one last info, what about point 2 of the first comment? 
Is it possible to introduce a simple check for the _Region3() function? I assume the problem is related to the line https://github.com/jjgomera/iapws/blob/master/iapws/iapws97.py#L1512 where x is set to 1 in any case. I suppose introducing something like:
```
if propiedades["h"] >= hc or propiedades["P"] >= Pc:
    propiedades["x"] = 1
else:
    propiedades["x"] = 0
```
can help to assign the yellow region to a liquid phase.
![Figure_11](https://github.com/jjgomera/iapws/assets/137185631/7f496a91-096b-4010-abee-ea8783a8fcd7)
Do you think it is correct? Or might this cause problems with other functions of the package?

**Comment by jjgomera** [comment]
Of course, again a great feedback!!, added in last commit.

**Comment by Nino-ndrk** [comment]
Hi, sorry for the delay, everything seems to work as expected, thanks a lot for the support.
