### ISSUE TITLE
Surface Tension, sigma, attribute error

### ISSUE THREAD

**Issue by spontarelliam** [jjgomera/iapws#8]
The surface tension, sigma, does not appear to be working. I receive the same attribute error in both Python 2.7.9 and 3.4.3.

```
from iapws import IAPWS97
sat_liquid=IAPWS97(T=370, x=0)            #saturated liquid with known T
print(sat_liquid.h) #calculated enthalpies
print(sat_liquid.sigma) #calculated surface tension

405.81466030352686
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-4e60866677df> in <module>()
      2 sat_liquid=IAPWS97(T=370, x=0)            #saturated liquid with known T
      3 print(sat_liquid.h) #calculated enthalpies
----> 4 print(sat_liquid.sigma)

AttributeError: 'IAPWS97' object has no attribute 'sigma'
```

**Comment by jjgomera** [comment]
Ups, a tiny bugs, iapws don't calculate sigma with Tx and Px definition when x value where 0 or 1.
Solved (i think) in last commit

**Comment by sskalisky** [comment]
I am having this same issue with calculating sigma using P and T definition. 
![image](https://user-images.githubusercontent.com/88901952/198088307-3506c78e-dc3a-4c96-bf18-4ac1dae4d1f8.png)

**Comment by jjgomera** [comment]
IAPWS97 only calculate surface tension in states with liquid phase, you're defining a state in vapor state so surface tension doesn't make physical sense
